language: node_js
dist: trusty
sudo: false
cache:
  directories:
    - node_modules
script:
  - yarn run ci
notifications:
  email: false
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE test;' -U postgres
addons:
  postgresql: '9.6'
  chrome: stable
